export const CHECKLIST_DOCUMENT_STATES = ['active', 'inactive'] as const;
export type ChecklistDocumentState = (typeof CHECKLIST_DOCUMENT_STATES)[number];

export const VISA_SERVICE_TYPE_VALUES = [
  'All',
  'University Admission',
  'Work Permit',
  'Investor Migration',
  'College Admission',
  'Student Visa',
  'Business Visa',
  'Permanent Residency',
  'Dependent Spouse',
  'Intra Office',
  'Visit Visa',
  'Tourist Visa',
  'Oppurtunity Card',
  'Job Seeker Visa',
  'Germany Opportunity Card',
  'Parent Visa RRV',
  'Australia GTI',
  'Australia Parent Visa',
  'Australia Child Visa',
  'Australia Partner Visa',
  'Parent Visa Australia SC804',
  'Australia RRV',
  'Child Visa Agreement Australia',
  'Retainer Agreement JSV Germany',
  'Parent Visa Australia retainer agreement',
  'EOI & Visa Stage 2',
  'Australia GTI Agreement',
  'Temporary Dependent Visa',
  'Australian Student Visa',
  'Visitor Visa Rejection',
  'Australia Work in Holiday Visa',
  'Germany Family Re-Union Visa',
  'Partner of Student Work Visa',
  'Business Visitor Visa',
  'Super Visa',
  'SC 403 Visa Application',
  'SC 400 Visa Application',
  'National Innovation Visa(NIV)',
] as const;

export type VisaServiceType = (typeof VISA_SERVICE_TYPE_VALUES)[number];

