'use strict';

/** Legacy sentinel — used only to find old mock tasks during cleanup */
const MOCK_CREATED_BY = '__mock_seed__';
const MOCK_TITLE_PREFIX = '[MOCK] ';
const MOCK_BATCH_DESC_PREFIX = 'Generated by seedMockApplicationTasks.js (batch:';

const STAFF_ROLES = ['master_admin', 'supervisor', 'team_leader', 'admin'];

const TASK_STATUSES = ['todo', 'in_progress', 'completed', 'cancelled'];
const TASK_LINK_TYPES = ['meeting', 'document', 'general'];

const DEFAULT_CLIENT_COUNT = 10;
const DEFAULT_TASKS_PER_CLIENT = 5;

const TITLE_TEMPLATES = [
  'Follow up on documents',
  'Schedule skills assessment call',
  'Review EOI submission',
  'Client check-in — lodgment deadline',
  'Verify passport copy',
  'Book medical appointment',
  'Prepare statement of purpose',
  'Confirm employment reference',
  'Upload police clearance',
  'Discuss visa outcome',
];

const DESCRIPTION_SNIPPETS = [
  'Please review the uploaded documents before our next call.',
  'Client requested a callback this week.',
  'Pending action from processing executive.',
  'Reminder to confirm appointment slot with client.',
  'Checklist item needs client attention.',
];

module.exports = {
  MOCK_CREATED_BY,
  MOCK_TITLE_PREFIX,
  MOCK_BATCH_DESC_PREFIX,
  STAFF_ROLES,
  TASK_STATUSES,
  TASK_LINK_TYPES,
  DEFAULT_CLIENT_COUNT,
  DEFAULT_TASKS_PER_CLIENT,
  TITLE_TEMPLATES,
  DESCRIPTION_SNIPPETS,
};
